operatives = [
    {   # Unit Template
        "opname":"",
        "stats":{
            "move":,
            "apl":,
            "gpact":,
            "def":,
            "save":,
            "wounds":,
        },
        "rweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":,
                        "skill":,
                        "dmg1":,
                        "dmg2":,
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":,
                        "skill":,
                        "dmg1":,
                        "dmg2":,
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
        "specials":[
        ],
    },
]