operatives = [
    {   # Guardian Defender [Warrior]
        "opname":"Guardian Defender [Warrior]",
        "stats":{
            "move":"6\"",
            "apl":"2",
            "gpact":"1",
            "def":"3",
            "save":"4+",
            "wounds":"8",
        },
        "rweaps":[
            {   # Shuriken Catapult
                "wname":"Shuriken Catapult",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"4",
                        "bskill":"3+",
                        "dmg":"3/4",
                        "srule":[
                        ],
                        "crits":[
                            "Rending"
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Fists
                "wname":"Fists",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"3",
                        "wskill":"3+",
                        "dmg":"2/3",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"Craftworld",
        "faction":[
            "Aeldari"
            "Asuryani"
        ],
        "house":"",
        "keywords":[
            "Guardian Defender"
            "Warrior"
        ],
    },
    {   # Guardian Defender [Heavy Gunner]
        "opname":"Guardian Defender [Heavy Gunner]",
        "stats":{
            "move":"6\"",
            "apl":"2",
            "gpact":"1",
            "def":"3",
            "save":"4+",
            "wounds":"8",
        },
        "rweaps":[
            {   # Shuriken Catapult
                "wname":"Shuriken Catapult",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"4",
                        "bskill":"3+",
                        "dmg":"3/4",
                        "srule":[
                        ],
                        "crits":[
                            "Rending"
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Fists
                "wname":"Fists",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"3",
                        "wskill":"3+",
                        "dmg":"2/3",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
            "Control Platform"
        ],
        "fackey":"Craftworld",
        "faction":[
            "Aeldari"
            "Asuryani"
        ],
        "house":"",
        "keywords":[
            "Guardian Defender"
            "Heavy Gunner"
        ],
    },
    {   # Unit Template
        "opname":"",
        "stats":{
            "move":"",
            "apl":"",
            "gpact":"",
            "def":"",
            "save":"",
            "wounds":"",
        },
        "rweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "bskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "wskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
    },
    {   # Unit Template
        "opname":"",
        "stats":{
            "move":"",
            "apl":"",
            "gpact":"",
            "def":"",
            "save":"",
            "wounds":"",
        },
        "rweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "bskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "wskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
    },
    {   # Unit Template
        "opname":"",
        "stats":{
            "move":"",
            "apl":"",
            "gpact":"",
            "def":"",
            "save":"",
            "wounds":"",
        },
        "rweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "bskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "wskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
    },
]