operatives = [
    {   # Guardian Defender [Warrior]
        "opname":"Guardian Defender [Warrior]",
        "stats":{
            "move":"6\"",
            "apl":"2",
            "gpact":"1",
            "def":"3",
            "save":"4+",
            "wounds":"8",
        },
        "rweaps":[
            {   # Shuriken Catapult
                "wname":"Shuriken Catapult",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "bskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Fists
                "wname":"Fists",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "wskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
    },
    {   # Unit Template
        "opname":"",
        "stats":{
            "move":"",
            "apl":"",
            "gpact":"",
            "def":"",
            "save":"",
            "wounds":"",
        },
        "rweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "bskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "wskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
    },
    {   # Unit Template
        "opname":"",
        "stats":{
            "move":"",
            "apl":"",
            "gpact":"",
            "def":"",
            "save":"",
            "wounds":"",
        },
        "rweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "bskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "wskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
    },
    {   # Unit Template
        "opname":"",
        "stats":{
            "move":"",
            "apl":"",
            "gpact":"",
            "def":"",
            "save":"",
            "wounds":"",
        },
        "rweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "bskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "mweaps":[
            {   # Weapon Template
                "wname":"",
                "profiles":[
                    {
                        "pname":"",
                        "atts":"",
                        "wskill":"",
                        "dmg":"",
                        "srule":[
                        ],
                        "crits":[
                        ],
                    },
                ]
            },
        ],
        "abs":[
        ],
        "uacts":[
        ],
        "fackey":"",
        "faction":[
        ],
        "house":"",
        "keywords":[
        ],
    },
]